FROM --platform=linux/amd64 gradle:8-jdk21 AS build
COPY . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle assemble
FROM --platform=linux/amd64 openjdk:21-slim
RUN mkdir /app
COPY --from=build /home/gradle/src/build/libs/*.jar /app/spring-boot-application.jar
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=production", "/app/spring-boot-application.jar"]
